FROM mysql:5.7.22
EXPOSE 3306
# COPY ./Calculadora/db/migrations/ /home/database/
# COPY ./Calculadora/db/dataset/ /home/database/
# COPY ./Calculadora/ci/init_database.sh/ /docker-entrypoint-initdb.d/init_database.sh